theme = "awesome-identity"
baseURL = "https://example.com"
title = "Awesome Identity for Hugo"


## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpg"
  firstname = "Shawn"
  lastname = "Yang"
  title = "Full-Stack Engineer"
  bio = """
  Hi, there, glad to see you on my webpage. I'm currently a postgraduate student at **UCLA** majoring in Electrical and Computer Engineering.

  I have one year full time professional experience at Huawei technology company specifying backend development for which I have a strong passion. 

  Aside from that, I'm so fascinated by the artifical intelligence stuff, the role of which in the fourth industrial revolution is same as that played by electricity in the second industrial revolution.
  
  Always interested in learning new technologies and tools, and docker is my favorit so far.  
  """
## Footer Configurations
[params.contacts]
github = "Shawn19960502"
email = "yangshuo960502@gmail.com"
[params.actions]
hello="hello"
[params.footer]
  copyright = "© 2019 Shawn Yang. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
