theme = "awesome-identity"
##//baseURL = "http://ysshawn.com"
title = "Shawn Yang's Personal webpage"

[params.meta]
  description = "Currently a postgraduate student at UCLA. Have Strong passion for backend development && Machine Learning."
  keywords = "Shawn Yang, Shuo, Shuo Yang, ysshawn, UCLA, ECE, Full Stack, backend, engineer, frontend, developer, architect"
  images = [
    "/images/profile.jpg"
  ]

## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpg"
  firstname = "Shawn"
  lastname = "Yang"
  title = "Software Engineer"
  bio = """
  Hi, there, glad to see you on my webpage. I'm currently a postgraduate student at **UCLA** majoring in Electrical and Computer Engineering.

  I have one year full time professional experience at Huawei technology company specifying backend development for which I have a strong passion. 
  
  Currently, I'm working at **Adobe** Corporated based in San Jose as an SDE summer intern(2020). 

  Aside from that, I'm so fascinated by the artifical intelligence stuff, the role of which in the fourth industrial revolution is same as that played by electricity in the second industrial revolution.
  
  Always interested in learning new technologies and tools, and Docker is my favorit so far.  
  """
## Footer Configurations
[params.contacts]
github = "Shawn19960502"
email = "yangshuo960502@gmail.com"

[[params.actions]]
  name = "Review My Resume"
  url = "http://ysshawn.com/public/resume.pdf"
[[params.actions]]
  name = "Project_S.Y.Mall"
  url = "http://mall.ysshawn.com"
[params.footer]
  copyright = "© 2020 Shawn Yang. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
